"""
PDF Invoice Generation Service.

Generates pharmacy invoice PDFs with customer data and order details using fpdf2.
Supports multilingual output based on the user's language.
"""

import os
import io
from datetime import datetime
from fpdf import FPDF


# --- Localization dictionaries ---
TRANSLATIONS = {
    "es": {
        "slogan": "Tu farmacia de confianza",
        "invoice_no": "Factura No",
        "date": "Fecha",
        "customer_section": "Datos del Cliente",
        "name": "Nombre",
        "doc_type": "Tipo de Documento",
        "doc_number": "Cedula de Ciudadania",
        "email": "Correo Electronico",
        "address": "Direccion",
        "city": "Ciudad",
        "phone": "Celular / Telefono",
        "products_section": "Detalle de Productos",
        "product": "Producto",
        "laboratory": "Laboratorio",
        "quantity": "Cantidad",
        "dosage": "Dosis",
        "unit_price": "Precio Unitario",
        "subtotal": "Subtotal",
        "total": "TOTAL:",
        "footer_disclaimer": "Este documento es una factura generada automaticamente por AI Explorer Pharmacy.",
        "page": "Pagina",
        "thank_you": (
            "Gracias por tu compra. Este documento sirve como comprobante de tu pedido. "
            "Si tienes alguna pregunta, no dudes en contactarnos."
        ),
    },
    "en": {
        "slogan": "Your trusted pharmacy",
        "invoice_no": "Invoice No",
        "date": "Date",
        "customer_section": "Customer Information",
        "name": "Name",
        "doc_type": "Document Type",
        "doc_number": "ID Number",
        "email": "Email",
        "address": "Address",
        "city": "City",
        "phone": "Phone",
        "products_section": "Product Details",
        "product": "Product",
        "laboratory": "Laboratory",
        "quantity": "Quantity",
        "dosage": "Dosage",
        "unit_price": "Unit Price",
        "subtotal": "Subtotal",
        "total": "TOTAL:",
        "footer_disclaimer": "This document is an invoice automatically generated by AI Explorer Pharmacy.",
        "page": "Page",
        "thank_you": (
            "Thank you for your purchase. This document serves as proof of your order. "
            "If you have any questions, feel free to contact us."
        ),
    },
    "fr": {
        "slogan": "Votre pharmacie de confiance",
        "invoice_no": "Facture No",
        "date": "Date",
        "customer_section": "Informations Client",
        "name": "Nom",
        "doc_type": "Type de Document",
        "doc_number": "Numero de Document",
        "email": "Email",
        "address": "Adresse",
        "city": "Ville",
        "phone": "Telephone",
        "products_section": "Detail des Produits",
        "product": "Produit",
        "laboratory": "Laboratoire",
        "quantity": "Quantite",
        "dosage": "Dosage",
        "unit_price": "Prix Unitaire",
        "subtotal": "Sous-total",
        "total": "TOTAL:",
        "footer_disclaimer": "Ce document est une facture generee automatiquement par AI Explorer Pharmacy.",
        "page": "Page",
        "thank_you": (
            "Merci pour votre achat. Ce document sert de preuve de votre commande. "
            "Si vous avez des questions, n'hesitez pas a nous contacter."
        ),
    },
}


def _get_translations(language: str) -> dict:
    """Returns the translation dict for the given language code. Defaults to Spanish."""
    lang = language.lower()[:2] if language else "es"
    return TRANSLATIONS.get(lang, TRANSLATIONS["es"])


class InvoicePDF(FPDF):
    """Custom PDF class for pharmacy invoices."""

    def __init__(self, translations: dict):
        super().__init__()
        self.set_auto_page_break(auto=True, margin=20)
        self._t = translations

    def header(self):
        """Renders the invoice header with pharmacy branding."""
        t = self._t
        # Logo / Pharmacy name
        self.set_font("Helvetica", "B", 20)
        self.set_text_color(33, 97, 140)
        self.cell(0, 10, "AI Explorer Pharmacy", ln=True, align="C")
        self.set_font("Helvetica", "", 9)
        self.set_text_color(100, 100, 100)
        self.cell(0, 5, t["slogan"], ln=True, align="C")
        self.ln(5)
        # Separator line
        self.set_draw_color(33, 97, 140)
        self.set_line_width(0.5)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(8)

    def footer(self):
        """Renders the invoice footer."""
        t = self._t
        self.set_y(-25)
        self.set_draw_color(33, 97, 140)
        self.set_line_width(0.3)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(3)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(130, 130, 130)
        self.cell(0, 5, t["footer_disclaimer"], ln=True, align="C")
        self.cell(0, 5, f"{t['page']} {self.page_no()}/{{nb}}", align="C")


def generate_invoice_pdf(
    customer_data: dict,
    products: list[dict],
    order_number: str | None = None,
    language: str = "es",
) -> bytes:
    """
    Generates an invoice PDF and returns it as bytes.

    Args:
        customer_data: Dict with keys:
            - nombre: str
            - tipo_documento: str
            - cedula: str
            - correo: str
            - direccion: str
            - ciudad: str
            - celular: str
        products: List of dicts with keys:
            - nombre: str
            - cantidad: int
            - precio_unitario: float
            - subtotal: float (precio_unitario * cantidad)
        order_number: Optional order reference number.
        language: Language code for the PDF content (e.g. "es", "en", "fr").

    Returns:
        PDF file content as bytes.
    """
    t = _get_translations(language)
    pdf = InvoicePDF(translations=t)
    pdf.alias_nb_pages()
    pdf.add_page()

    # --- Invoice metadata ---
    if not order_number:
        order_number = f"FAC-{datetime.now().strftime('%Y%m%d%H%M%S')}"

    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(33, 33, 33)
    pdf.cell(0, 7, f"{t['invoice_no']}: {order_number}", ln=True)
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(0, 6, f"{t['date']}: {datetime.now().strftime('%d/%m/%Y %H:%M')}", ln=True)
    pdf.ln(6)

    # --- Customer information section ---
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(33, 97, 140)
    pdf.cell(0, 8, t["customer_section"], ln=True)
    pdf.set_draw_color(200, 200, 200)
    pdf.set_line_width(0.2)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(3)

    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(33, 33, 33)

    customer_fields = [
        (t["name"], customer_data.get("nombre", "")),
        (t["doc_type"], customer_data.get("tipo_documento", "")),
        (t["doc_number"], customer_data.get("cedula", "")),
        (t["email"], customer_data.get("correo", "")),
        (t["address"], customer_data.get("direccion", "")),
        (t["city"], customer_data.get("ciudad", "")),
        (t["phone"], customer_data.get("celular", "")),
    ]

    for label, value in customer_fields:
        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(55, 6, f"{label}:", align="L")
        pdf.set_font("Helvetica", "", 10)
        pdf.cell(0, 6, str(value), ln=True)

    pdf.ln(8)

    # --- Products table ---
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(33, 97, 140)
    pdf.cell(0, 8, t["products_section"], ln=True)
    pdf.ln(2)

    # Table header
    pdf.set_fill_color(33, 97, 140)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 8)

    col_widths = [50, 30, 20, 30, 30, 30]  # Product, Lab, Qty, Dosage, Unit Price, Subtotal
    headers = [t["product"], t["laboratory"], t["quantity"], t["dosage"], t["unit_price"], t["subtotal"]]

    for i, header in enumerate(headers):
        pdf.cell(col_widths[i], 8, header, border=1, align="C", fill=True)
    pdf.ln()

    # Table rows
    pdf.set_text_color(33, 33, 33)
    pdf.set_font("Helvetica", "", 8)
    fill = False
    total = 0.0

    for product in products:
        if fill:
            pdf.set_fill_color(240, 248, 255)
        else:
            pdf.set_fill_color(255, 255, 255)

        nombre = str(product.get("nombre", ""))
        laboratorio = str(product.get("laboratorio", "N/A"))
        dosis = str(product.get("dosis", "N/A"))
        cantidad = int(product.get("cantidad", 1))
        precio_unitario = float(product.get("precio_unitario", 0))
        subtotal = float(product.get("subtotal", precio_unitario * cantidad))
        total += subtotal

        pdf.cell(col_widths[0], 7, nombre[:28], border=1, align="L", fill=True)
        pdf.cell(col_widths[1], 7, laboratorio[:16], border=1, align="C", fill=True)
        pdf.cell(col_widths[2], 7, str(cantidad), border=1, align="C", fill=True)
        pdf.cell(col_widths[3], 7, dosis[:16], border=1, align="C", fill=True)
        pdf.cell(col_widths[4], 7, f"{precio_unitario:,.2f} COP", border=1, align="R", fill=True)
        pdf.cell(col_widths[5], 7, f"{subtotal:,.2f} COP", border=1, align="R", fill=True)
        pdf.ln()
        fill = not fill

    # Total row
    pdf.ln(4)
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(33, 97, 140)
    total_label_width = col_widths[0] + col_widths[1] + col_widths[2] + col_widths[3] + col_widths[4]
    pdf.cell(total_label_width, 9, f"{t['total']}  ", align="R")
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(col_widths[5], 9, f" {total:,.2f} COP", border=1, align="R")
    pdf.ln(15)

    # --- Footer note ---
    pdf.set_font("Helvetica", "I", 9)
    pdf.set_text_color(100, 100, 100)
    pdf.multi_cell(0, 5, t["thank_you"])

    # Return PDF as bytes
    return bytes(pdf.output())
