"""
Report PDF Generation Service.

Generates PDF reports containing data tables and chart images using fpdf2.
Used when the AI generates charts/tables and the user wants them sent via email.
"""

import io
import re
from datetime import datetime
from fpdf import FPDF


def _sanitize_for_pdf(text: str) -> str:
    """Removes emojis and non-latin1 characters from text for safe PDF rendering with Helvetica."""
    if not text:
        return ""
    # Remove emoji and other non-BMP characters (above U+FFFF)
    text = re.sub(r'[\U00010000-\U0010FFFF]', '', text)
    # Remove remaining characters outside latin-1 range (above U+00FF)
    # but keep common accented chars (U+00C0 to U+00FF)
    result = []
    for ch in text:
        if ord(ch) <= 0xFF:
            result.append(ch)
        elif ch in '\u2013\u2014\u2018\u2019\u201c\u201d':
            # Replace common typographic chars with ASCII equivalents
            replacements = {'\u2013': '-', '\u2014': '-', '\u2018': "'", '\u2019': "'", '\u201c': '"', '\u201d': '"'}
            result.append(replacements.get(ch, ''))
        else:
            # Skip the character
            result.append('')
    return ''.join(result).strip()


# --- Localization dictionaries for reports ---
REPORT_TRANSLATIONS = {
    "es": {
        "title": "Reporte de Datos",
        "slogan": "Tu farmacia de confianza",
        "generated_on": "Generado el",
        "query": "Consulta",
        "summary": "Resumen",
        "data_table": "Tabla de Datos",
        "chart_included": "Grafico incluido en la siguiente pagina",
        "footer_disclaimer": "Este reporte fue generado automaticamente por AI Explorer Pharmacy.",
        "page": "Pagina",
        "no_data": "No se encontraron datos para esta consulta.",
    },
    "en": {
        "title": "Data Report",
        "slogan": "Your trusted pharmacy",
        "generated_on": "Generated on",
        "query": "Query",
        "summary": "Summary",
        "data_table": "Data Table",
        "chart_included": "Chart included on the next page",
        "footer_disclaimer": "This report was automatically generated by AI Explorer Pharmacy.",
        "page": "Page",
        "no_data": "No data found for this query.",
    },
    "fr": {
        "title": "Rapport de Donnees",
        "slogan": "Votre pharmacie de confiance",
        "generated_on": "Genere le",
        "query": "Requete",
        "summary": "Resume",
        "data_table": "Tableau de Donnees",
        "chart_included": "Graphique inclus a la page suivante",
        "footer_disclaimer": "Ce rapport a ete genere automatiquement par AI Explorer Pharmacy.",
        "page": "Page",
        "no_data": "Aucune donnee trouvee pour cette requete.",
    },
}


def _get_report_translations(language: str) -> dict:
    """Returns the translation dict for the given language code."""
    lang = language.lower()[:2] if language else "es"
    return REPORT_TRANSLATIONS.get(lang, REPORT_TRANSLATIONS["es"])


class ReportPDF(FPDF):
    """Custom PDF class for data reports."""

    def __init__(self, translations: dict):
        super().__init__()
        self.set_auto_page_break(auto=True, margin=20)
        self._t = translations

    def header(self):
        """Renders the report header with pharmacy branding."""
        t = self._t
        self.set_font("Helvetica", "B", 18)
        self.set_text_color(33, 97, 140)
        self.cell(0, 10, "AI Explorer Pharmacy", ln=True, align="C")
        self.set_font("Helvetica", "", 9)
        self.set_text_color(100, 100, 100)
        self.cell(0, 5, t["slogan"], ln=True, align="C")
        self.ln(3)
        self.set_draw_color(33, 97, 140)
        self.set_line_width(0.5)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(6)

    def footer(self):
        """Renders the report footer."""
        t = self._t
        self.set_y(-20)
        self.set_draw_color(33, 97, 140)
        self.set_line_width(0.3)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(3)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(130, 130, 130)
        self.cell(0, 4, t["footer_disclaimer"], ln=True, align="C")
        self.cell(0, 4, f"{t['page']} {self.page_no()}/{{nb}}", align="C")


def generate_report_pdf(
    user_query: str,
    summary_text: str,
    columns: list[str],
    rows: list[tuple],
    chart_image_bytes: bytes | None = None,
    language: str = "es",
) -> bytes:
    """
    Generates a report PDF with a data table and optional chart image.

    Args:
        user_query: The original user question/query.
        summary_text: The AI-generated summary of the data.
        columns: List of column names for the data table.
        rows: List of row tuples for the data table.
        chart_image_bytes: Optional PNG bytes of the chart image.
        language: Language code for the PDF content ('es', 'en', 'fr').

    Returns:
        PDF file content as bytes.
    """
    t = _get_report_translations(language)
    pdf = ReportPDF(translations=t)
    pdf.alias_nb_pages()
    pdf.add_page()

    # --- Report title ---
    pdf.set_font("Helvetica", "B", 14)
    pdf.set_text_color(33, 33, 33)
    pdf.cell(0, 8, t["title"], ln=True, align="C")
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 5, f"{t['generated_on']}: {datetime.now().strftime('%d/%m/%Y %H:%M')}", ln=True, align="C")
    pdf.ln(8)

    # --- User query section ---
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(33, 97, 140)
    pdf.cell(0, 7, t["query"], ln=True)
    pdf.set_draw_color(200, 200, 200)
    pdf.set_line_width(0.2)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(3)
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(33, 33, 33)
    # Wrap long queries — sanitize to remove emojis
    pdf.multi_cell(0, 5, _sanitize_for_pdf(user_query[:500]))
    pdf.ln(6)

    # --- Summary section ---
    if summary_text:
        pdf.set_font("Helvetica", "B", 11)
        pdf.set_text_color(33, 97, 140)
        pdf.cell(0, 7, t["summary"], ln=True)
        pdf.set_draw_color(200, 200, 200)
        pdf.line(10, pdf.get_y(), 200, pdf.get_y())
        pdf.ln(3)
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(33, 33, 33)
        pdf.multi_cell(0, 5, _sanitize_for_pdf(summary_text[:1000]))
        pdf.ln(6)

    # --- Data table section ---
    if columns and rows:
        pdf.set_font("Helvetica", "B", 11)
        pdf.set_text_color(33, 97, 140)
        pdf.cell(0, 7, t["data_table"], ln=True)
        pdf.ln(3)

        # Calculate column widths based on content
        num_cols = len(columns)
        available_width = 190  # Page width minus margins
        col_widths = _calculate_col_widths(columns, rows, available_width, num_cols)

        # Table header
        pdf.set_fill_color(33, 97, 140)
        pdf.set_text_color(255, 255, 255)
        pdf.set_font("Helvetica", "B", 7)

        for i, col in enumerate(columns):
            pdf.cell(col_widths[i], 7, _truncate(_sanitize_for_pdf(col), col_widths[i], pdf), border=1, align="C", fill=True)
        pdf.ln()

        # Table rows
        pdf.set_text_color(33, 33, 33)
        pdf.set_font("Helvetica", "", 7)
        fill = False
        max_rows = 50  # Limit rows in PDF to prevent oversized files

        for row_idx, row in enumerate(rows[:max_rows]):
            if fill:
                pdf.set_fill_color(240, 248, 255)
            else:
                pdf.set_fill_color(255, 255, 255)

            for i, value in enumerate(row):
                cell_text = _truncate(_sanitize_for_pdf(str(value) if value is not None else ""), col_widths[i], pdf)
                pdf.cell(col_widths[i], 6, cell_text, border=1, align="C", fill=True)
            pdf.ln()
            fill = not fill

        if len(rows) > max_rows:
            pdf.ln(2)
            pdf.set_font("Helvetica", "I", 8)
            pdf.set_text_color(100, 100, 100)
            pdf.cell(0, 5, f"... y {len(rows) - max_rows} filas mas.", ln=True, align="C")

        pdf.ln(6)
    elif not columns and not rows:
        pdf.set_font("Helvetica", "I", 10)
        pdf.set_text_color(100, 100, 100)
        pdf.cell(0, 7, t["no_data"], ln=True, align="C")
        pdf.ln(6)

    # --- Chart image section ---
    if chart_image_bytes:
        # Check if we need a new page for the chart
        if pdf.get_y() > 180:
            pdf.add_page()

        pdf.set_font("Helvetica", "B", 11)
        pdf.set_text_color(33, 97, 140)
        pdf.cell(0, 7, "Chart / Grafico", ln=True)
        pdf.ln(3)

        # Save chart image to a temporary buffer and embed
        import tempfile
        import os

        tmp_path = os.path.join(tempfile.gettempdir(), "report_chart_tmp.png")
        with open(tmp_path, "wb") as f:
            f.write(chart_image_bytes)

        try:
            # Fit the chart image to the page width
            pdf.image(tmp_path, x=15, w=180)
        except Exception as e:
            pdf.set_font("Helvetica", "I", 9)
            pdf.set_text_color(150, 50, 50)
            pdf.cell(0, 5, f"Error embedding chart: {str(e)[:80]}", ln=True)
        finally:
            try:
                os.remove(tmp_path)
            except OSError:
                pass

    return bytes(pdf.output())


def _calculate_col_widths(columns: list[str], rows: list[tuple], available_width: float, num_cols: int) -> list[float]:
    """Calculates proportional column widths based on content length."""
    if num_cols == 0:
        return []

    # Calculate max content length for each column
    max_lengths = []
    for i in range(num_cols):
        col_max = len(columns[i])
        for row in rows[:20]:  # Sample first 20 rows
            val_len = len(str(row[i])) if i < len(row) and row[i] is not None else 0
            col_max = max(col_max, val_len)
        max_lengths.append(col_max)

    total_length = sum(max_lengths) or 1
    widths = [(l / total_length) * available_width for l in max_lengths]

    # Ensure minimum width
    min_width = 15
    for i in range(len(widths)):
        if widths[i] < min_width:
            widths[i] = min_width

    # Normalize to fit available width
    total_w = sum(widths)
    if total_w > available_width:
        factor = available_width / total_w
        widths = [w * factor for w in widths]

    return widths


def _truncate(text: str, col_width: float, pdf: FPDF) -> str:
    """Truncates text to fit within the given column width."""
    # Approximate character limit based on column width and font size
    char_limit = int(col_width / 2.2)  # rough approximation for font size 7
    if len(text) > char_limit:
        return text[:char_limit - 2] + ".."
    return text
